### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by juasiepo**
command line to generate the password hash added

### CODE REVIEW

**Review by bryansullins — CHANGES_REQUESTED** [review]
I would like to leave in the line about openssl since it is more commonly installed on Linux distros, and we can add the line for mkpasswd into the README if you like.

**Comment by juasiepo** [comment]
> 
> 
> I would like to leave in the line about openssl since it is more commonly installed on Linux distros, and we can add the line for mkpasswd into the README if you like.

Neither **openssl** nor **mkpasswd** are a proper requirement as once the password has been "hashed" they are not needed anymore.

Of course both can be there :)

I used **mkpasswd** as after several attempts I didn't find the proper syntax to use the openssl. Can you please add the  openssl syntax too? So users can use both options

**Comment by bryansullins** [comment]
Juan,

I pushed the change to master. See how it strikes you, and if you like, you
can make your addition - thanks for contributing!

Bryan Sullins

**Comment by juasiepo** [comment]
Not neccesary anymore

**Pull request closed without merging**
